/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WSNFrame2.java
 *
 * Created on May 27, 2011, 3:56:43 PM
 */

package GUI;

import EnumDefinitionPackage.DistributionTypeEnum;
import EnumDefinitionPackage.IntruderTypeEnum;
import EnumDefinitionPackage.SensingTypeEnum;
import IntruderDetectionWSN.GUIBasedIntruderDetectionDriver;

/**
 *
 * @author KuttaA
 */
public class WSNFrame extends javax.swing.JFrame
{
    /** Creates new form WSNFrame2 */
    public WSNFrame() {

        initComponents();

        jSensingRange.setValue(50);
        jCommunicationRange.setValue(100);

        jTextSensingRange.setText("50.0");
        jTextCommunicationRange.setText("100.0");
        
        jTextNumIterations.setText("50");
        
        jKValue.setEnabled(false);
    }

    public void disableSlider() {
       jKValue.setEnabled(false);
    }

    public void enableSlider() {
        jKValue.setEnabled(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTextKValue = new javax.swing.JTextField();
        jKValue = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSensingRange = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        jCommunicationRange = new javax.swing.JSlider();
        jDetectionMethod = new javax.swing.JComboBox();
        jTextSensingRange = new javax.swing.JTextField();
        jTextCommunicationRange = new javax.swing.JTextField();
        jAnimateSingleRun = new javax.swing.JButton();
        jComputeAvgDistance = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jTextNumIterations = new javax.swing.JTextField();
        jNumIterations = new javax.swing.JSlider();
        jLabel9 = new javax.swing.JLabel();
        jDistributionType = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Straight Line Intruder Detection");

        jTextKValue.setEditable(false);
        jTextKValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextKValue.setText("3");

        jKValue.setMaximum(10);
        jKValue.setValue(3);
        jKValue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jKValueStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText("Select the K Value");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("Communication Range (m)");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setText("Sensing Range (m)");

        jSensingRange.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSensingRangeStateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setText("Detection Method");

        jCommunicationRange.setMaximum(200);
        jCommunicationRange.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCommunicationRangeStateChanged(evt);
            }
        });

        jDetectionMethod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single Detection", "K - Detections", "K - Coverage" }));
        jDetectionMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDetectionMethodActionPerformed(evt);
            }
        });

        jTextSensingRange.setEditable(false);
        jTextSensingRange.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextSensingRange.setText("Sensing Range");

        jTextCommunicationRange.setEditable(false);
        jTextCommunicationRange.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextCommunicationRange.setText("jTextField1");

        jAnimateSingleRun.setText("Animate Single Run");
        jAnimateSingleRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAnimateSingleRunActionPerformed(evt);
            }
        });

        jComputeAvgDistance.setText("Compute Intruder Distance");
        jComputeAvgDistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComputeAvgDistanceActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Common Variables");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Average Intruder Distance Specific Variables");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Number of Iterations");

        jTextNumIterations.setEditable(false);
        jTextNumIterations.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextNumIterations.setText("jTextField1");

        jNumIterations.setMajorTickSpacing(10);
        jNumIterations.setMaximum(1000);
        jNumIterations.setMinimum(1);
        jNumIterations.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jNumIterationsStateChanged(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Distribution Type");

        jDistributionType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Random", "Triangle", "Square" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jTextCommunicationRange, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCommunicationRange, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jTextSensingRange, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSensingRange, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jTextKValue, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jKValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jDistributionType, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jDetectionMethod, javax.swing.GroupLayout.Alignment.LEADING, 0, 254, Short.MAX_VALUE))))
                                .addGap(52, 52, 52))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jAnimateSingleRun, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComputeAvgDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextNumIterations, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jNumIterations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 13, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDistributionType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDetectionMethod, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextKValue)
                    .addComponent(jKValue, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSensingRange, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextSensingRange))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCommunicationRange, javax.swing.GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(jTextCommunicationRange))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jNumIterations, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextNumIterations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAnimateSingleRun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComputeAvgDistance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jKValueStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jKValueStateChanged
        // TODO add your handling code here:
        jTextKValue.setText(Integer.toString(jKValue.getValue()));
    }//GEN-LAST:event_jKValueStateChanged

    private void jSensingRangeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSensingRangeStateChanged
        // TODO add your handling code here:
        Double newValue = jSensingRange.getValue()*2.0;
        jTextSensingRange.setText(Integer.toString(jSensingRange.getValue()));
        jTextCommunicationRange.setText(Double.toString(newValue));
        jCommunicationRange.setValue(newValue.intValue());
}//GEN-LAST:event_jSensingRangeStateChanged

    private void jCommunicationRangeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCommunicationRangeStateChanged
        // TODO add your handling code here:
        Double newValue = Math.floor(jCommunicationRange.getValue()/2.0);
        jTextCommunicationRange.setText(Integer.toString(jCommunicationRange.getValue()));
        jTextSensingRange.setText(Double.toString(newValue));
        jSensingRange.setValue(newValue.intValue());
}//GEN-LAST:event_jCommunicationRangeStateChanged

    private void jDetectionMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDetectionMethodActionPerformed
        if ( jDetectionMethod.toString().contains("K"))
            enableSlider();
        else
            disableSlider();
}//GEN-LAST:event_jDetectionMethodActionPerformed

private void jAnimateSingleRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAnimateSingleRunActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jAnimateSingleRunActionPerformed

private void jComputeAvgDistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComputeAvgDistanceActionPerformed
    // TODO add your handling code here:

    SensingTypeEnum sType;

    switch (jDetectionMethod.getSelectedIndex()) {
        case 0:
            sType = SensingTypeEnum.SINGLE_DETECTION;
            break;
        case 1:
            sType = SensingTypeEnum.K_INDIVIDUAL;
            break;
        case 2:
            sType = SensingTypeEnum.K_SIMULTANEOUS;
            break;
        default:
            sType = SensingTypeEnum.SINGLE_DETECTION;
    }

    DistributionTypeEnum dType;

    switch( jDistributionType.getSelectedIndex() ) {
        case 0:
            dType = DistributionTypeEnum.RANDOM;
            break;
        case 1:
            dType = DistributionTypeEnum.TRIANGLE;
            break;
        case 2:
            dType = DistributionTypeEnum.SQUARE;
            break;
        default:
            dType = DistributionTypeEnum.RANDOM;
    }

    Integer sRange = jSensingRange.getValue();
    Integer cRange = jCommunicationRange.getValue();

    if ( WSNDriver != null ) return; // Only keep track of 1 thread

    ProgressAndResults frame = new ProgressAndResults(jNumIterations.getValue());
    frame.setSize(356,321);
    frame.pack();

    WSNDriver = new GUIBasedIntruderDetectionDriver();
    WSNDriver.initialize(sType,
            dType,
            IntruderTypeEnum.STRAIGHT_LINE, 
            sRange.floatValue(),
            cRange.floatValue(),
            jNumIterations.getValue(),
            jKValue.getValue(),
            this,                    // parent so we can be notified when thread finishes
            frame
            );

    WSNDriver.start();
    DisableAllControls();
    frame.setTitle("Average Intruder Distance - ");
    frame.setVisible(true);
}//GEN-LAST:event_jComputeAvgDistanceActionPerformed

public void threadFinished() {
    Double avgDist = WSNDriver.getAverageDistance();
    WSNDriver = null;
    EnableAllControls();
}

private void jNumIterationsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jNumIterationsStateChanged
    // TODO add your handling code here:
    jTextNumIterations.setText(Integer.toString(jNumIterations.getValue()));
}//GEN-LAST:event_jNumIterationsStateChanged


private GUIBasedIntruderDetectionDriver WSNDriver;



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAnimateSingleRun;
    private javax.swing.JSlider jCommunicationRange;
    private javax.swing.JButton jComputeAvgDistance;
    private javax.swing.JComboBox jDetectionMethod;
    private javax.swing.JComboBox jDistributionType;
    private javax.swing.JSlider jKValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSlider jNumIterations;
    private javax.swing.JSlider jSensingRange;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextCommunicationRange;
    private javax.swing.JTextField jTextKValue;
    private javax.swing.JTextField jTextNumIterations;
    private javax.swing.JTextField jTextSensingRange;
    // End of variables declaration//GEN-END:variables

    private void DisableAllControls() {
    jAnimateSingleRun.setEnabled(false);
    jCommunicationRange.setEnabled(false);
    jComputeAvgDistance.setEnabled(false);
    jDetectionMethod.setEnabled(false);
    jDistributionType.setEnabled(false);
    jKValue.setEnabled(false);
    jNumIterations.setEnabled(false);
    jSensingRange.setEnabled(false);
    }

    private void EnableAllControls() {
    jAnimateSingleRun.setEnabled(true);
    jCommunicationRange.setEnabled(true);
    jComputeAvgDistance.setEnabled(true);
    jDetectionMethod.setEnabled(true);
    jDistributionType.setEnabled(true);
    jKValue.setEnabled(true);
    jNumIterations.setEnabled(true);
    jSensingRange.setEnabled(true);
    }
 }
